version: "3.8"

services:
  nginx:
    container_name: store-api-nginx
    build:
      context: .
      dockerfile: docker/nginx/Dockerfile
    ports:
      - "80:80"
    links:
      - php-fpm
    volumes:
      - ./:/var/www/html

  php-fpm:
    container_name: store-api-fpm
    build:
      context: .
      dockerfile: docker/php-fpm/Dockerfile
    volumes:
      - ./:/var/www/html
    links:
      - postgres

  postgres:
    image: postgres:14.4
    container_name: store-api-postgres
    env_file:
      - .env
    ports:
        - "5432:5432"
    volumes:
      - ../laravel-api-postgres/data:/var/lib/postgresql/data
