FROM nginx:alpine

COPY docker/nginx/laravel.conf /etc/nginx/conf.d/default.conf

RUN apk update \
    && apk upgrade \
    && apk --update add logrotate \
    && apk add --no-cache openssl \
    && apk add --no-cache bash

RUN set -x ; \
    addgroup -g 82 -S www-data ; \
    adduser -u 82 -D -S -G www-data www-data && exit 0 ; exit 1

WORKDIR /var/www/html

EXPOSE 80

